### ISSUE TITLE
Wrong python version in call_peaks rule

### ISSUE THREAD

**Issue by SichongP** [kernco/functional-annotation#1]
I got this warning message when running until call_peaks rule:
```
Conda environment defines Python version < 3.5. Using Python of the master process to execute script. Note that this cannot be avoided, because the script uses data structures from Snakemake which are Python >=3.5 only.
/home/pengsc/miniconda3/bin/python /finno/data/users/sichong/FAANG/Nuclei_ATAC/.snakemake/scripts/tmp9qued067.CallPeaks.py
```
The python it uses instead is version 3.6.6 and the script it's calling is CallPeaks.py

Then I got this error in macs2 run:
```
ImportError: /home/pengsc/.cache/Python-Eggs/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg-tmp/MACS2/IO/Parser.so: undefined symbol: PyFPE_jbuf
```
Which seems to result from a python version not being 2.7?

I was able to run macs2 separately on tagAlign files generated by previous steps successfully so bypassing this step is no problem. But I'm wondering if this is related to how snakemake sets up conda environment or is it simply a problem of my env setup?

**Comment by kernco** [comment]
I'm not sure what is causing that error. What is the command you're using to run the pipeline?

**Comment by SichongP** [comment]
```
snakemake -j 10 -s ../functional-annotaion/Snakefile --configfile config.yaml -p -k --use-conda
```

And here is my config file:
```
tissues: [FrozenNuclei]
reps: [A]
narrow_peaks: [CTCF]
broad_peaks: [ATAC]
inputs: None
no_input: [ATAC]
genome: /share/finnolab/reference/equCab2.0/UCSC/assembly/genome.fa
genomesize: 2474929062
annotation: /share/finnolab/reference/equCab2.0/UCSC/annotation/Genes/genes.gtf
mapq: 30
ChromHMM_genome: EquCab2
chromsizes: /share/finnolab/reference/equCab2.0/UCSC/equCab2.chrom.sizes
```

I'm running it on our pilot data so it has no replicates.
Also, I'm not sure how to run it only on ATAC data. If I remove narrow peak line or give it "None", the pipeline failed to run. Putting CTCF there gives me a bunch of failed run on CTCF analysis but otherwise it seems fine.

**Comment by kernco** [comment]
I realized it shouldn't be calling the CallPeaks.py script for ATAC-seq peaks. That was a bug I fixed but hadn't uploaded to Github (I just did, though). I don't know if that will fix your issue, though. But the peaks you called already might have been called with the Macs2 parameters for broad histone modification marks, which is different from what's used when doing ATAC-seq peak calling.

**Comment by SichongP** [comment]
Ah I see. Good thing I asked. Thanks!

**Comment by SichongP** [comment]
So I tried new pipeline and I'm still getting the same error from macs2:
```
Traceback (most recent call last):
  File "/finno/data/users/sichong/FAANG/analysis/.snakemake/conda/6324b035/bin/macs2", line 617, in <module>
    main()
  File "/finno/data/users/sichong/FAANG/analysis/.snakemake/conda/6324b035/bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/OptValidator.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 6, in __bootstrap__
ImportError: /home/pengsc/.cache/Python-Eggs/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg-tmp/MACS2/IO/Parser.so
: undefined symbol: PyFPE_jbuf
[Thu Nov  8 16:27:56 2018]
Error in rule call_atac_peaks:
    jobid: 39
    output: Macs2/ATAC_FrozenLiver_repA_peaks.broadPeak
    conda-env: /finno/data/users/sichong/FAANG/analysis/.snakemake/conda/6324b035

RuleException:
CalledProcessError in line 180 of /finno/data/users/sichong/FAANG/functional-annotation/Rules/CallPeaks.smk:
Command 'source activate /finno/data/users/sichong/FAANG/analysis/.snakemake/conda/6324b035; set -euo pipefail;
  macs2 callpeak -t Aligned_Reads/ATAC_FrozenLiver_repA.bam -f BAM -n Macs2/ATAC_FrozenLiver_repA -g 2474929062
 -q 0.05 --broad --nomodel --shift -100 --extsize 200 ' returned non-zero exit status 1.
  File "/finno/data/users/sichong/FAANG/functional-annotation/Rules/CallPeaks.smk", line 180, in __rule_call_atac_peaks
  File "/home/pengsc/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Job failed, going on with independent jobs.
```

Edit:
On a separate run it seemed to have finished this step with no hiccups. Could this have anything to do with GNU screen that I was using to run the two separate runs on? They were otherwise the same.

**Comment by SichongP** [comment]
Turns out my PYTHONPATH was somehow altered and that broke my conda. It went through perfectly after I corrected it. Thanks!
