### ISSUE TITLE
Chipseq analysis without input control

### ISSUE THREAD

**Issue by yinshiyi** [kernco/functional-annotation#6]
in the geo
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE158430

there is no input control sample
Can you share how did you get around this no control issue?
Thank you

**Comment by kernco** [comment]
Sorry, it was an oversight that it did not get uploaded. The input data is available here: http://farm.cse.ucdavis.edu/~ckern/FAANG_Data/

Note the "Input_Library_Mapping.txt" files in each folder that indicate which input libraries go with which ChIP library.

**Comment by yinshiyi** [comment]
thank you very much for getting back to me
i want to bring to your attention the difference between NCBI fastq and the fastq you provided
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12697205
CTCF from UC Davis FAANG pig adipose rep P348
and 
http://farm.cse.ucdavis.edu/~ckern/FAANG_Data/Pig/CTCF_Adipose_P348.fq.gz
they have difference amounts of total reads

Could you take a look when you have time? thank you
